/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoadatos.MateriaData;
import entidades.Materias;
/**
 *
 * @author santi
 */
public class Materia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Materia
     */
    public Materia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JLabel();
        jnombre1 = new javax.swing.JLabel();
        jano = new javax.swing.JLabel();
        jestado1 = new javax.swing.JLabel();
        jnuevo1 = new javax.swing.JButton();
        jeliminar1 = new javax.swing.JButton();
        jguardar1 = new javax.swing.JButton();
        jsalir1 = new javax.swing.JButton();
        jbuscar1 = new javax.swing.JButton();
        TextCodigo = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextAno = new javax.swing.JTextField();
        RadioActivo = new javax.swing.JRadioButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Materia");

        jcodigo.setText("Codigo");

        jnombre1.setText("Nombre");

        jano.setText("Año");

        jestado1.setText("Estado");

        jnuevo1.setText("Reactivar");
        jnuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnuevo1ActionPerformed(evt);
            }
        });

        jeliminar1.setText("Eliminar");
        jeliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeliminar1ActionPerformed(evt);
            }
        });

        jguardar1.setText("Guardar");
        jguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jguardar1ActionPerformed(evt);
            }
        });

        jsalir1.setText("Salir");

        jbuscar1.setText("Bucar");
        jbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jcodigo)
                                            .addGap(46, 46, 46))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jnombre1)
                                            .addGap(42, 42, 42)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jano)
                                        .addGap(60, 60, 60)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextAno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbuscar1)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jnuevo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jeliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jestado1)
                                        .addGap(49, 49, 49)
                                        .addComponent(RadioActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jguardar1)
                                        .addGap(48, 48, 48)))
                                .addComponent(jsalir1)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodigo)
                    .addComponent(jbuscar1)
                    .addComponent(TextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jeliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnuevo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnombre1)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jano)
                    .addComponent(TextAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioActivo)
                    .addComponent(jestado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jguardar1)
                    .addComponent(jsalir1))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jguardar1ActionPerformed
        // TODO add your handling code here:
        String Nombre = TextNombre.getText();
        int Anio = Integer.parseInt(TextAno.getText());
        boolean Estado = RadioActivo.isSelected();
       
       
        
        Materias nuevo = new Materias(Nombre, Anio, Estado);
        MateriaData mat = new MateriaData();
        mat.guardarMateria(nuevo);


    }//GEN-LAST:event_jguardar1ActionPerformed

    private void jbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuscar1ActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt(TextCodigo.getText());
        
        MateriaData Mat = new MateriaData();
        Mat.buscarMateria(Codigo);
        
    }//GEN-LAST:event_jbuscar1ActionPerformed

    private void jeliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeliminar1ActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt(TextCodigo.getText());
        
        MateriaData Mat = new MateriaData();
        Mat.eliminarMateria(Codigo);
    }//GEN-LAST:event_jeliminar1ActionPerformed

    private void jnuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnuevo1ActionPerformed
        // TODO add your handling code here:
        int Codigo = Integer.parseInt(TextCodigo.getText());
        
        MateriaData Mat = new MateriaData();
        Mat.ReactivarMateria(Codigo);
    }//GEN-LAST:event_jnuevo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioActivo;
    private javax.swing.JTextField TextAno;
    private javax.swing.JTextField TextCodigo;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jano;
    private javax.swing.JButton jbuscar1;
    private javax.swing.JLabel jcodigo;
    private javax.swing.JButton jeliminar1;
    private javax.swing.JLabel jestado1;
    private javax.swing.JButton jguardar1;
    private javax.swing.JLabel jnombre1;
    private javax.swing.JButton jnuevo1;
    private javax.swing.JButton jsalir1;
    // End of variables declaration//GEN-END:variables
}
